# see https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

# conda build -c conda-forge --python 3.10 fab

package:
  name: fab
  version: "0.10.1"

source:
  git_url: https://github.com/metomi/fab.git
  git_rev: 0.10.1

requirements:
  host:
    - python
    - pip
  run:
    - fparser
    - libclang
    - python
    - pip
    - python-clang

test:
  imports:
    - fab

about:
  home: https://github.com/metomi/fab
