
name: sci-fab
dependencies:
  - flake8
  - gfortran
  - libclang
  - mypy
  - openmpi
  - python=3.8
  - pip=21.2.4
  - pytest
  - python-clang
  - pytest-cov
  - pytest-mock
  - pip:
      - fparser
