@startuml

partition "file walking" {
    (*) --> "TreeDescent.descend()"
    "TreeDescent.descend()" -->[file path] SourceVisitor.visit()
}

"SourceVisitor.visit()" -->[artifact] "Fab._queue"

"Fab._queue" -->[artifact] "queue _worker"

"queue _worker" -->[artifact] "Engine.process()"

"Engine.process()" -->[call] "<b>tasks</b>
preprocessors
analysers
compilers
linkers
pragma injectors
c/fortran processors
" as tasks

tasks -->[artifacts] "Engine.process()"

"Engine.process()" -->[artifacts] "queue _worker"

"queue _worker" -->[artifacts] "Fab._queue"

@enduml
