name: QA

on:
  push:
    branches:
      - main
      - v*.*
  pull_request:
    branches:
      - main
      - v*.*

concurrency:
  # cancel any in-progress runs for the same group (branch/tag) {{github.ref}}
  # if a new run is triggered, except for the main branch
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  checks:

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.11', '3.12', '3.13']

    steps:
      # This step does not need a GA cache
      - name: Setup Compiler
        run: |
          # clang-19 (no matching version in PyPi)
          # sudo wget -qO /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
          #   https://apt.llvm.org/llvm-snapshot.gpg.key
          # echo "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc) main" \
          #   | sudo tee /etc/apt/sources.list.d/apt.llvm.org.list
          # sudo apt update -y
          # sudo apt install -y gcc gfortran
          # sudo apt install -y clang-19 libclang-19-dev

          # echo "Installed Clang versions:"
          # clang --version
          # clang-19 --version

          # clang 20

          wget -O - https://apt.llvm.org/llvm.sh | sudo bash -s -- 20
          sudo apt update -y
          sudo apt install -y gcc gfortran plocate
          sudo apt install -y clang-20 libclang-20-dev
          sudo updatedb

          # Set clang-20 as the default clang version
          sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-20/bin/clang-20 200
          sudo update-alternatives --config clang

          echo "===Installed Compiler versions:"
          set -x
          clang --version
          clang-20 --version
          gcc --version
          gfortran --version

          locate libclang.so
          locate libclang-20.so
          set +x

          # sudo apt install -y llvm clang libclang-dev gcc gfortran

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # The clang binding version has to match the version in the Ubuntu being used.
      - name: Install Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install clang==20.1.5
          pip install .[dev]
          pip install .[docs]

      - name: Type check with mypy
        run: python -m mypy source tests

      - name: Code style check with flake8
        if: always()
        run: flake8 . --count --show-source --statistics

      - name: Unit tests with Pytest
        if: always()
        run: |
          export LD_LIBRARY_PATH=/usr/lib/llvm-20/lib:$LD_LIBRARY_PATH
          python -m pytest --cov=fab tests/unit_tests

      - name: System tests with Pytest
        if: always()
        run: python -m pytest --cov=fab tests/system_tests

      # Sphinx linkcheck can potentially detect false negatives due to network
      # issues or slow responses. To avoid failing the build due to these
      # issues, we set continue-on-error to true
      - name: Link Checks
        if: always()
        working-directory: Documentation
        run: |
          sphinx-build -q -b linkcheck \
            -d build/doctrees source build/linkcheck || true
          echo "== Ignored and Redirected links, if any =="
          jq -c 'select([.status] | inside(["ignored", "redirected"]))' \
            build/linkcheck/output.json
        continue-on-error: true
