name: Legal

on:
  pull_request_target:

jobs:
  cla:
    uses: MetOffice/growss/.github/workflows/cla-check.yaml@main
    with:
      runner: 'ubuntu-24.04'
      cla-url: 'https://github.com/MetOffice/Momentum/blob/main/CLA.md'
