
name: Picasso Build

on: workflow_dispatch
# It's undesirable to trigger from PRs because it needs permissions for the forked repo,
# which have possible security implications.
#on: [push, pull_request]

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Build fab image
        uses: MetOffice/picasso-build-images-action@v1
        with:
          images: '[{"name": "image", "path": "envs/picasso/image.yml", "tag": "latest"}]'
